#!/usr/bin/env python

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""
The entry point script
"""

import sys
from multiprocessing import freeze_support

# TODO WARNING temp monkey patch fix to prevent warnings
# START >>>
from gi.importer import DynamicImporter

if DynamicImporter.load_module:
    # SEE: https://gitlab.gnome.org/GNOME/pygobject/-/issues/494
    # these 2 methods must be implimented.
    def create_module(self, spec):
        return self.load_module(spec.name)

    def exec_module(_self, _module):
        return

    DynamicImporter.create_module = create_module
    DynamicImporter.exec_module = exec_module
# <<< END

if __name__ == "__main__":
    freeze_support()
    from bauble import main

    sys.exit(main.main())
